services:
  - type: web
    name: denofthemoondragon3
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
